name: Send TSC meeting agenda to email list
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: timheuer/issue-notifier@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'tac@openmainframeproject.org'
        toMailAddress: '[MAILING LIST EMAIL]'
        subject: 'TSC meeting agenda'
        labelsToMonitor: 'meeting'
